/**
 * Utility helper functions for formatting, exports, and language setups.
 */

import { ReviewResult, Language } from "./types";

// Map file extensions to supported languages
export function getLanguageFromFilename(filename: string): Language {
  const ext = filename.split(".").pop()?.toLowerCase();
  switch (ext) {
    case "py":
      return Language.PYTHON;
    case "js":
    case "jsx":
      return Language.JAVASCRIPT;
    case "ts":
    case "tsx":
      return Language.TYPESCRIPT;
    case "java":
      return Language.JAVA;
    case "cpp":
    case "h":
    case "hpp":
    case "cc":
      return Language.CPP;
    case "go":
      return Language.GO;
    case "rs":
      return Language.RUST;
    default:
      return Language.JAVASCRIPT;
  }
}

// Generate an elegant Markdown report
export function generateMarkdownReport(review: ReviewResult): string {
  const criticalBugs = review.issues.filter(i => i.severity === "critical");
  const securityIssues = review.issues.filter(i => i.category === "security");
  const performanceIssues = review.issues.filter(i => i.category === "performance");
  const styleIssues = review.issues.filter(i => i.category === "style" || i.category === "architecture");

  return `# Code Review Report: ${review.title}
Generated by AI Senior Code Critic on ${new Date(review.createdAt).toLocaleDateString()}

## 📊 Overview
- **Overall Code Score**: **${review.overallScore}/100**
- **Language**: \`${review.language.toUpperCase()}\`
- **Complexity Metrics**:
  - **Time Complexity**: \`${review.complexity.timeComplexity}\`
  - **Space Complexity**: \`${review.complexity.spaceComplexity}\`
  - **Cyclomatic Complexity**: \`${review.complexity.cyclomaticComplexity}\`
  - **Maintainability Index**: \`${review.complexity.maintainabilityIndex}/100\`

---

## 📝 Executive Summary
${review.executiveSummary}

---

## 🛑 Critical Issues & Bugs (${criticalBugs.length})
${
  criticalBugs.length === 0
    ? "_No critical bugs detected. Well done!_"
    : criticalBugs
        .map(
          (bug, idx) => `
### ${idx + 1}. [Line ${bug.line || "N/A"}] ${bug.title}
- **Description**: ${bug.description}
${bug.snippet ? `\n\`\`\`${review.language}\n${bug.snippet}\n\`\`\`` : ""}
- **Remediation**: ${bug.remediation || "N/A"}`
        )
        .join("\n")
}

---

## 🔒 Security Vulnerabilities (${securityIssues.length})
${
  securityIssues.length === 0
    ? "_No high-priority security issues found._"
    : securityIssues
        .map(
          (sec, idx) => `
### ${idx + 1}. [Line ${sec.line || "N/A"}] ${sec.title}
- **Severity**: ${sec.severity.toUpperCase()}
- **Threat**: ${sec.description}
- **Remediation**: ${sec.remediation || "N/A"}`
        )
        .join("\n")
}

---

## ⚡ Performance Improvements (${performanceIssues.length})
${
  performanceIssues.length === 0
    ? "_No critical bottlenecks detected._"
    : performanceIssues
        .map(
          (perf, idx) => `
### ${idx + 1}. ${perf.title}
- **Description**: ${perf.description}
- **Impact**: ${perf.remediation || "N/A"}`
        )
        .join("\n")
}

---

## 🎨 Best Practices & Architecture Suggestions (${styleIssues.length})
${
  styleIssues.length === 0
    ? "_Code matches professional design patterns and SOLID practices._"
    : styleIssues
        .map(
          (style, idx) => `
### ${idx + 1}. [Line ${style.line || "N/A"}] ${style.title}
- **Rule/Concept**: ${style.category.toUpperCase()}
- **Recommendation**: ${style.description}`
        )
        .join("\n")
}

---

## 💡 Refactored Implementation Proposal
Here is an improved, fully cleaned and refactored version of your submitted code block:

\`\`\`${review.language}
${review.refactoredCode}
\`\`\`
`;
}

// Download markdown file
export function downloadMarkdown(review: ReviewResult) {
  const content = generateMarkdownReport(review);
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", `code_review_${review.id}.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

// Download HTML / Printable Layout (equivalent to beautiful PDF report)
export function downloadPrintableHTML(review: ReviewResult) {
  const mdReport = generateMarkdownReport(review);
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const htmlContent = `
    <html>
      <head>
        <title>AI Code Review Report - ${review.title}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            color: #1f2937;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
            line-height: 1.6;
          }
          h1 { color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px; }
          h2 { color: #1f2937; margin-top: 30px; border-bottom: 1px solid #f3f4f6; padding-bottom: 6px; }
          h3 { color: #374151; margin-top: 20px; }
          pre { background-color: #f3f4f6; border: 1px solid #e5e7eb; padding: 16px; border-radius: 6px; overflow-x: auto; font-family: monospace; }
          code { font-family: monospace; background-color: #f3f4f6; padding: 2px 4px; border-radius: 4px; }
          .badge { display: inline-block; padding: 4px 8px; border-radius: 9999px; font-size: 12px; font-weight: 600; text-transform: uppercase; }
          .badge-score { background-color: #dbeafe; color: #1e40af; }
          .badge-critical { background-color: #fee2e2; color: #991b1b; }
          .metrics { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; background-color: #f9fafb; padding: 16px; border-radius: 8px; margin: 20px 0; }
          .metric-box { border-left: 4px solid #3b82f6; padding-left: 12px; }
          @media print {
            body { padding: 0; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="no-print" style="margin-bottom: 20px; text-align: right;">
          <button onclick="window.print()" style="padding: 8px 16px; background: #2563eb; color: white; border: none; border-radius: 4px; cursor: pointer;">Print to PDF</button>
        </div>
        <h1>Code Review: ${review.title}</h1>
        <div class="metrics">
          <div class="metric-box">
            <strong>Overall Score:</strong> <span class="badge badge-score">${review.overallScore}/100</span>
          </div>
          <div class="metric-box">
            <strong>Language:</strong> <code>${review.language}</code>
          </div>
          <div class="metric-box">
            <strong>Time Complexity:</strong> <code>${review.complexity.timeComplexity}</code>
          </div>
          <div class="metric-box">
            <strong>Space Complexity:</strong> <code>${review.complexity.spaceComplexity}</code>
          </div>
        </div>
        
        <h2>Executive Summary</h2>
        <p>${review.executiveSummary.replace(/\n\n/g, "</p><p>").replace(/\n/g, "<br>")}</p>

        <h2>Issues Detected</h2>
        ${review.issues.map(issue => `
          <div style="margin-bottom: 24px; border: 1px solid #f3f4f6; border-radius: 6px; padding: 16px;">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
              <strong style="font-size: 16px;">${issue.title}</strong>
              <span class="badge" style="background-color: ${issue.severity === "critical" ? "#fee2e2; color: #991b1b;" : "#fef3c7; color: #92400e;"}">${issue.severity}</span>
            </div>
            <p style="margin: 4px 0;"><strong>Category:</strong> ${issue.category} | <strong>Line:</strong> ${issue.line || "N/A"}</p>
            <p style="margin: 8px 0; color: #4b5563;">${issue.description}</p>
            ${issue.remediation ? `<p style="margin-top: 8px; color: #047857; background-color: #ecfdf5; padding: 8px; border-radius: 4px;"><strong>Remediation:</strong> ${issue.remediation}</p>` : ""}
          </div>
        `).join("")}

        <h2>Refactored Code Suggestion</h2>
        <pre><code>${review.refactoredCode.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</code></pre>
      </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
}

// Sample initial greeting codes as guidance/starter code snippets
export const SAMPLE_CODES = {
  [Language.PYTHON]: `def calculate_fibonacci_list(n):
    # CRITICAL: Highly inefficient recursion + memory leaks!
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    
    # Nested recursive definitions without memoization
    def fib(x):
        if x <= 0: return 0
        if x == 1: return 1
        return fib(x-1) + fib(x-2)
        
    results = []
    for i in range(n):
        # O(2^N) loop inside loop!
        results.append(fib(i))
    return results

# SQL Injection risk inside helper
def fetch_user_dashboard(db_connection, auth_email):
    cursor = db_connection.cursor()
    # String interpolation leads to high SQL injection threat!
    query = "SELECT * FROM users WHERE email = '" + auth_email + "' AND active = True"
    cursor.execute(query)
    return cursor.fetchall()
`,
  [Language.JAVASCRIPT]: `// Legacy Javascript - Callback hell, no error control, var leaking
function loadWorkspaceData(userId, callback) {
  var db = require("./db-connection");
  
  db.query("SELECT * FROM profiles WHERE id = " + userId, function(err, profile) {
    if (err) {
      // Swallows error silently!
      console.log("error occured but whatever");
    }
    
    db.query("SELECT * FROM projects WHERE owner_id = " + profile.id, function(err, projects) {
      db.query("SELECT * FROM tasks WHERE project_id = " + projects[0].id, function(err, tasks) {
        // Memory Leak: holding references to all DB connections
        global.loadedAppCache = { profile: profile, projects: projects, tasks: tasks };
        callback(tasks);
      });
    });
  });
}
`,
  [Language.TYPESCRIPT]: `// TypeScript violation list: Any types everywhere, non-null assertions, blocking loops
import * as fs from 'fs';

export class DataSynchronizer {
  private cache: any = {}; // Type safety failure

  public async syncLocalData(filePath: string): Promise<any> {
    try {
      // Inefficient synchronous IO inside an async system block
      const fileContent = fs.readFileSync(filePath, 'utf-8');
      const parsed = JSON.parse(fileContent);
      
      this.cache[filePath] = parsed;
      
      // Infinite-ish loop risk if items reference parents recursively
      for (const item of parsed.items) {
        if (item.dependencies) {
          this.syncLocalData(item.dependencies.file); // Might cycle indefinitely
        }
      }
      return parsed;
    } catch (e) {
      console.error(e);
      return (null as any); // Defeating the typechecker
    }
  }
}
`,
  [Language.JAVA]: `package com.reviewer.app;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;

public class InventoryManager {
    // Shared state violation - Not thread-safe!
    private static int lastTransactionId = 0;
    
    public void restockItem(Connection conn, String itemId, int quantity) {
        try {
            // SQL Injection vulnerability!
            Statement stmt = conn.createStatement();
            String sql = "UPDATE inventory SET stock = stock + " + quantity + " WHERE id = '" + itemId + "'";
            stmt.executeUpdate(sql); // Statement never closed! Resource leak.
            
            lastTransactionId = lastTransactionId + 1; // Thread safety issue
        } catch (Exception e) {
            e.printStackTrace(); // Sweeps exception details under printStreams
        }
    }
}
`,
  [Language.CPP]: `#include <iostream>
#include <cstring>

class BufferOverflow {
public:
    // Classic vulnerability - Buffer overflow and Memory leak!
    void processHeaderInput(const char* userInput) {
        char* secureBuffer = new char[32]; // Hardcoded size without validation
        
        // Risky unsafe copy function! Buffer overflow hazard.
        strcpy(secureBuffer, userInput);
        
        std::cout << "Successfully read metadata header: " << secureBuffer << std::endl;
        
        // Memory Leak! Deconstruct never deletes secureBuffer pointer.
    }
};
`,
  [Language.GO]: `package main

import (
	"fmt"
	"sync"
)

// Data Race state issue
var globalCounter int = 0

func updateCountersConcurrently() {
	var wg sync.WaitGroup
	for i := 0; i < 1000; i++ {
		wg.Add(1)
		go func() {
			// CRITICAL: Writing to shared variable concurrently without a Mutex lock!
			globalCounter++
			wg.Done()
		}()
	}
	wg.Wait()
	fmt.Println("Completed counts:", globalCounter)
}
`,
  [Language.RUST]: `// Unsafe block abusing and bypass borrowchecker
fn modify_shared_pointer_unsafe(raw_ptr: *mut i32) {
    unsafe {
        // High risk pointer dereference without checking if null
        *raw_ptr = 9999;
        
        // Re-creating or freeing manually, violating safety constraints
        let boxed = Box::from_raw(raw_ptr);
        println!("Value reclaimed: {:?}", boxed);
        // Will double free when leaving scope!
    }
}
`
};
